### ISSUE TITLE
Add input interface

### ISSUE THREAD

**Issue by OlivieFranklova** [AbsaOSS/datasets-similarity#24]
```[tasklist]
### Tasks
- [ ] new package for inputs
- [ ] interface for inputs
- [ ] csv file input implementation
```

**Comment by OlivieFranklova** [comment]
After rethinking the system design structure, this ticket is obsolete
