### ISSUE TITLE
Add user interface

### ISSUE THREAD

**Issue by OlivieFranklova** [AbsaOSS/datasets-similarity#26]
~~Extend #16 CLI as  UI~~
```[tasklist]
### Tasks
- [x] new package for user interfaces outside of similarity package
- [x] basic UI just run the app by python runer "name of directory"
- [x] #25 
```

Removed task
- [x] ~~move CLI to new package~~
depend on #28

**Comment by OlivieFranklova** [comment]
This will be resolved in https://github.com/AbsaOSS/datasets-similarity/issues/16
