### ISSUE TITLE
Models and interfaces

### ISSUE THREAD

**Issue by OlivieFranklova** [AbsaOSS/datasets-similarity#28]
Create Interfaces for connector and UI.
**Connector:**
 Data source <-> Connector <-> Similarity
Connector should connect, load data and format them
*Models*
- Connector settings model
- Connector output model

**UI**
UI <-> Similarity
*Models*
- Settings model
- Similarity result model
```[tasklist]
### Tasks
- [x] new interface package in similarity
- [x] new models package in similarity
- [x] Connector interface
- [x] UI interface
- [x] models 
- [x] https://github.com/AbsaOSS/datasets-similarity/issues/26
- [x] https://github.com/AbsaOSS/datasets-similarity/issues/23
```
