### ISSUE TITLE
Edit README.md

### ISSUE THREAD

**Issue by OlivieFranklova** [AbsaOSS/datasets-similarity#30]
It should solve notes from PR #21 

**Notes**
* In README in How to run, I would expect sub-chapters describing how to reach variant: two variant of similarity and column2vec
* DataShow looks like three features. I saw only one line in README.
* Consider a more detailed table of contents for users looking for exact parts.* 

```[tasklist]
### Tasks
- [ ] Add sub chapters about similarity variants
- [ ] Add sub chapter about column2Vec
- [ ] Describe DataShow properly
- [ ] Improve table of contents (add subsections of run - black, pylint ..., )
- [ ] Add links to other READMEs
```
