### ISSUE TITLE
Running parallel column2Vec tests

### ISSUE THREAD

**Issue by OlivieFranklova** [AbsaOSS/datasets-similarity#32]
- column2Vec tests are not run in PR 

```[tasklist]
### Tasks
- [ ] Add job to workflows
- [ ] solve parallel run for column2vec tests
- [ ] resolve skipped tests
```
could be related to #19
