### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by OlivieFranklova** [AbsaOSS/datasets-similarity#40]
## Metadata

```[tasklist]
### Tasks
- [x] move correlated columns from default to compute_correlation
- [x] remove get_column_type and get_column_kind from DataframeMetadata
- [x] rename DataframeMetadata -> Metadata, DataFrameMetadataCreator -> MetadataCreator
- [ ] size should be weight and height
- [x] rename  type_column to column_type
- [ ] QUESTION what to give an upper class for all specific metadata and then not have 3 dictionaries but only one. Then it would not be necessary to detect the type and then the metadata
- [x] HIGH KindMetadata should be separeted from ID, BOOL, Constant
- [x] add correlation computation
```

## MetadataCreator

```[tasklist]
### Tasks
- [ ] Add file for configuration column_incomplete_trashold
- [x] add correlation computation
```

## Project structure

```[tasklist]
### Tasks
- [x] rename column2Vec -> column2vec
- [ ] root folder should contain only these folders similarity and column2vec ( except .github etc )
- [ ] similarity and column2vec will have similar structure ( tests, tests/data, tests/data_validation, docs/images/... )
- [x] folders impl -> src
- [ ] [Optional] documentation has root README.md which points to similarity/docs/... or docs/...
```
